# Generated by Django 5.1.1 on 2024-10-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('img', models.ImageField(blank=True, null=True, upload_to='projetos/%Y/%m')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
