# Generated by Django 5.1.1 on 2024-10-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='img',
            new_name='image',
        ),
    ]
